// 90 Official Canva Font Combinations extracted directly from Canva's Text Panel
export interface CanvaOfficialTextCombo {
  id: string;
  label: string;
  img: string;
  primaryText: string;
  subText?: string;
  fontKey?: string;
  color?: string;
  fontSize?: number;
  textTransform?: string;
  letterSpacing?: string;
}

export const CANVA_OFFICIAL_TEXT_COMBOS: CanvaOfficialTextCombo[] = [
  {
    id: "canva-official-001",
    label: "Happy Birthday",
    img: "https://template.canva.com/EADYfsBCn6U/2/0/270w-D1A-K22_7K8.png",
    primaryText: "Happy Birthday",
    subText: "WISHING YOU THE BEST",
    fontKey: "serif",
    color: "#D97706",
    fontSize: 42,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-002",
    label: "Golden Hour",
    img: "https://template.canva.com/EAFxf5AnnE8/2/0/340w-aS4NcEKJFLo.png",
    primaryText: "GOLDEN HOUR",
    subText: "SUMMER COLLECTION",
    fontKey: "serif",
    color: "#D97706",
    fontSize: 36,
    textTransform: "uppercase",
    letterSpacing: "0.1em",
  },
  {
    id: "canva-official-003",
    label: "Fun Retro Script Thank You Echo Text Effect",
    img: "https://template.canva.com/EAD87yXxksg/3/0/308w-75E1IiqVNyg.png",
    primaryText: "Thank You",
    subText: "FOR YOUR SUPPORT",
    fontKey: "script",
    color: "#4B5563",
    fontSize: 40,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-004",
    label: "Happy Birthday! Text in White Red Style",
    img: "https://template.canva.com/EAGDHqd92QM/2/0/228w-_AtH9WIytBU.png",
    primaryText: "Happy Birthday",
    subText: "WISHING YOU THE BEST",
    fontKey: "serif",
    color: "#E11D48",
    fontSize: 42,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-005",
    label: "Pink Bold Glow Neon Text Effect",
    img: "https://template.canva.com/EAD876-5-YQ/3/0/514w-1xmSEL7OCrM.png",
    primaryText: "PINK BOLD GLOW",
    subText: "",
    fontKey: "display",
    color: "#EC4899",
    fontSize: 36,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  {
    id: "canva-official-006",
    label: "Thank You Text Effect in Red White Style",
    img: "https://template.canva.com/EAGDH3UTISI/2/0/766w-bMdbF0TYWZI.png",
    primaryText: "Thank You",
    subText: "FOR YOUR SUPPORT",
    fontKey: "serif",
    color: "#E11D48",
    fontSize: 40,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-007",
    label: "Like & Subscribe Text Effect in Yellow Red Hollow Style",
    img: "https://template.canva.com/EAFxq94Nw24/1/0/300w-KHW8b65gXoA.png",
    primaryText: "LIKE & SUBSCRIBE",
    subText: "DON'T FORGET TO SHARE",
    fontKey: "display",
    color: "#F59E0B",
    fontSize: 36,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  {
    id: "canva-official-008",
    label: "Modern Script",
    img: "https://template.canva.com/EADYfrGkTvM/2/0/350w-lBYRrd7tu1k.png",
    primaryText: "Modern Script",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-009",
    label: "Order Now Text Effect in Light Blue Orange Shadow Style",
    img: "https://template.canva.com/EAFxf_YlAbI/2/0/786w-U__zGnXtJ00.png",
    primaryText: "Order Now",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-010",
    label: "Diskon",
    img: "https://template.canva.com/EADae-L9NSI/2/0/778w-WsPjQpPLkJI.png",
    primaryText: "DISKON",
    subText: "SPESIAL HARI INI",
    fontKey: "sans-bold",
    color: "#DC2626",
    fontSize: 44,
    textTransform: "uppercase",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-011",
    label: "Bride&Groom Text Effect in Black Style",
    img: "https://template.canva.com/EAGuIXZJz74/1/0/234w-zqOiHIvlGBU.png",
    primaryText: "Bride & Groom",
    subText: "TOGETHER FOREVER",
    fontKey: "serif",
    color: "#1F2937",
    fontSize: 38,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-012",
    label: "Now Open!",
    img: "https://template.canva.com/EAFxfyz1JRg/2/0/478w-JfoU1_w9Mh0.png",
    primaryText: "NOW OPEN",
    subText: "WELCOME EVERYONE",
    fontKey: "display",
    color: "#10B981",
    fontSize: 36,
    textTransform: "uppercase",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-013",
    label: "Coming Soon Text Effect in Bright Yellow Lift Style",
    img: "https://template.canva.com/EAFxqytOpjk/2/0/336w-_o7sbKIdQI8.png",
    primaryText: "COMING SOON",
    subText: "STAY TUNED",
    fontKey: "display",
    color: "#D97706",
    fontSize: 36,
    textTransform: "uppercase",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-014",
    label: "Text Holder | Memo Address",
    img: "https://template.canva.com/EADYfmDZ5sw/2/0/1376w-Du1qwM_KMns.png",
    primaryText: "Text Holder",
    subText: "",
    fontKey: "serif",
    color: "#374151",
    fontSize: 28,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-015",
    label: "Coming Soon Stay Tuned E-Commerce Text Effect in Dark Red White Trendy Business Style",
    img: "https://template.canva.com/EAGEmKxUptk/2/0/304w-2jjFY7BM7aU.png",
    primaryText: "COMING SOON",
    subText: "STAY TUNED",
    fontKey: "display",
    color: "#B91C1C",
    fontSize: 36,
    textTransform: "uppercase",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-016",
    label: "30% Off Text Effect in White Mint Green Style",
    img: "https://template.canva.com/EAGDHw5b42w/2/0/682w-kBs5UIwNNkY.png",
    primaryText: "30% OFF",
    subText: "LIMITED TIME ONLY",
    fontKey: "sans-bold",
    color: "#DC2626",
    fontSize: 44,
    textTransform: "uppercase",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-017",
    label: "Wedding & Event Planning Text Effect in Dark Blue Style",
    img: "https://template.canva.com/EAGiJDw-m-E/1/0/222w-ZU7IFMjkWtU.png",
    primaryText: "Our Wedding",
    subText: "JOIN OUR CELEBRATION",
    fontKey: "serif",
    color: "#1F2937",
    fontSize: 38,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-018",
    label: "Title, Heading",
    img: "https://template.canva.com/EADYfkobM-U/2/0/612w-Hg-wIrHpvJQ.png",
    primaryText: "Title, Heading",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-019",
    label: "Glowing Yellow Script Sparkle Neon Text Effect",
    img: "https://template.canva.com/EAD87wrs7KI/3/0/538w-figjQ0CF5R4.png",
    primaryText: "GLOWING YELLOW SCRIPT SPARKLE",
    subText: "",
    fontKey: "display",
    color: "#EAB308",
    fontSize: 36,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  {
    id: "canva-official-020",
    label: "TATTOO studio",
    img: "https://template.canva.com/EAGEx2kaAtw/2/0/784w-zHnzYHA9i1Q.png",
    primaryText: "TATTOO studio",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-021",
    label: "Talk to us",
    img: "https://template.canva.com/EADYfl0cWd4/2/0/844w-ufqpUZ5xLWs.png",
    primaryText: "Talk to us",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-022",
    label: "Blue and Violet Gamer Level Up Neon Text Effect",
    img: "https://template.canva.com/EAD873byWxI/3/0/412w-nQ3KwvY2a5o.png",
    primaryText: "BLUE AND VIOLET GAMER LEVEL UP",
    subText: "",
    fontKey: "display",
    color: "#06B6D4",
    fontSize: 36,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  {
    id: "canva-official-023",
    label: "Bold Yellow Business Huge Sale Hollow Text EffectEffect",
    img: "https://template.canva.com/EAD872Vi-D0/2/0/352w-FThRzjCR1Gc.png",
    primaryText: "BIG SALE",
    subText: "UP TO 50% OFF",
    fontKey: "sans-bold",
    color: "#DC2626",
    fontSize: 44,
    textTransform: "uppercase",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-024",
    label: "Shares are Appreciated Text Effect in Mint Green Curve Style",
    img: "https://template.canva.com/EAFxkEFkk4E/2/0/774w-OvdKAnPboyQ.png",
    primaryText: "Shares are Appreciated",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-025",
    label: "Stats",
    img: "https://template.canva.com/EADYfgqlfGg/2/0/286w-HaLx43nk370.png",
    primaryText: "Stats",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-026",
    label: "Men's Clothing Label",
    img: "https://template.canva.com/EADYfh4jyoI/2/0/342w-PXNBx1zBOsQ.png",
    primaryText: "Men's Clothing Label",
    subText: "",
    fontKey: "serif",
    color: "#374151",
    fontSize: 28,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-027",
    label: "Bright Purple Video Game Play Glitch Text  Effect",
    img: "https://template.canva.com/EAD87_1Bgdc/2/0/788w--YlEXRLQl-8.png",
    primaryText: "Bright Purple Video Game Pla...",
    subText: "",
    fontKey: "display",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-028",
    label: "Like & Follow For More Text Effect in Light Yellow Lift Style",
    img: "https://template.canva.com/EAFxq5C7Zek/1/0/266w-52snVA22SVA.png",
    primaryText: "LIKE & SUBSCRIBE",
    subText: "DON'T FORGET TO SHARE",
    fontKey: "display",
    color: "#F59E0B",
    fontSize: 36,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  {
    id: "canva-official-029",
    label: "Modern Sale Text Group",
    img: "https://template.canva.com/EADYfu8Do-g/2/0/952w-fI91PJ5p5ds.png",
    primaryText: "BIG SALE",
    subText: "UP TO 50% OFF",
    fontKey: "sans-bold",
    color: "#DC2626",
    fontSize: 44,
    textTransform: "uppercase",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-030",
    label: "Join Now Text Effect in Neon Pink White Style",
    img: "https://template.canva.com/EAGDH-t4LGM/2/0/216w-UhPW9G0kSyg.png",
    primaryText: "JOIN NOW",
    subText: "",
    fontKey: "display",
    color: "#EC4899",
    fontSize: 36,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  {
    id: "canva-official-031",
    label: "Pink Script Sweet Echo Text Effect",
    img: "https://template.canva.com/EAD872448kA/2/0/786w-G0yMQAG3pPY.png",
    primaryText: "Pink Script Sweet Echo",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-032",
    label: "Brand Storytelling & Content Creation Text Effect in Dark Blue Light Blue Style",
    img: "https://template.canva.com/EAGiOXqPy0k/1/0/234w-AeE2hIkIe_4.png",
    primaryText: "Brand Storytelling & Content...",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-033",
    label: "Seasonal (Spring/Summer) Marketing & Promotions Text Effect in Green Dark Green Style",
    img: "https://template.canva.com/EAGiJESelkQ/1/0/228w-V5S1t5lnJj8.png",
    primaryText: "Seasonal (Spring/Summer) Mar...",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-034",
    label: "Bright Green Sporty Hustle Hollow Text Effect",
    img: "https://template.canva.com/EAD87zSa5og/2/0/402w-jl34k_gRDTE.png",
    primaryText: "Bright Green Sporty Hustle H...",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-035",
    label: "Great Energy Text Effect in Black Style",
    img: "https://template.canva.com/EAG142T8Bl0/1/0/248w-f9GUb-80mLY.png",
    primaryText: "Great Energy",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-036",
    label: "Great work!",
    img: "https://template.canva.com/EAGTmlFuS1k/3/0/666w-VguAn1ijCdw.png",
    primaryText: "Great work!",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-037",
    label: "Like & Subscribe Text Effect in Purple Dark Blue Happy Hippie Style",
    img: "https://template.canva.com/EAGblHuckVA/2/0/644w-txeMaXvY88M.png",
    primaryText: "LIKE & SUBSCRIBE",
    subText: "DON'T FORGET TO SHARE",
    fontKey: "display",
    color: "#8B5CF6",
    fontSize: 36,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  {
    id: "canva-official-038",
    label: "Flourescent Bright Bold Planet Arcadia Glitch Text Effect",
    img: "https://template.canva.com/EAD87_5ZiY8/2/0/372w-sMs2B1tQDlw.png",
    primaryText: "Flourescent Bright Bold Plan...",
    subText: "",
    fontKey: "display",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-039",
    label: "Family Time Text Effect in Bronze Lift Style",
    img: "https://template.canva.com/EAFxqzFPar8/2/0/402w-ZQcj_OV9REg.png",
    primaryText: "Family Time",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-040",
    label: "Retro Bright Game On Glitch Text Effect",
    img: "https://template.canva.com/EAD87_gGBLI/2/0/332w-8Ha2ohnA9hI.png",
    primaryText: "Retro Bright Game On Glitch",
    subText: "",
    fontKey: "display",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-041",
    label: "Modern Wedding Text Group",
    img: "https://template.canva.com/EADYfi0SaeI/2/0/326w-HCCZEZxHMPo.png",
    primaryText: "Our Wedding",
    subText: "JOIN OUR CELEBRATION",
    fontKey: "serif",
    color: "#1F2937",
    fontSize: 38,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-042",
    label: "Blue Wood Label",
    img: "https://template.canva.com/EADYfuHUTkE/2/0/1240w-5d7ApRc3kQk.png",
    primaryText: "Blue Wood Label",
    subText: "",
    fontKey: "serif",
    color: "#374151",
    fontSize: 28,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-043",
    label: "Fashion Icon Text Effect in Black Style",
    img: "https://template.canva.com/EAG149UREkQ/1/0/324w-4eyhcCuuFPE.png",
    primaryText: "Fashion Icon",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-044",
    label: "Bold Green and Blue Workout Echo Text Effect",
    img: "https://template.canva.com/EAD870WLsG0/2/0/370w-vG7VTFB3d5g.png",
    primaryText: "Bold Green and Blue Workout ...",
    subText: "",
    fontKey: "display",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-045",
    label: "Visual Trends & Font Styles Text Effect in Black Style",
    img: "https://template.canva.com/EAGiJCCY_SY/1/0/172w-P5lt9LGlGWQ.png",
    primaryText: "Visual Trends & Font Styles",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-046",
    label: "Vibe Text Effect in Burgundy Pink Style",
    img: "https://template.canva.com/EAG14wj8eUU/1/0/756w-vd4g4L64Clc.png",
    primaryText: "Vibe",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-047",
    label: "Welcome home!",
    img: "https://template.canva.com/EADYfrO25Uo/2/0/326w-sToG7Wzsv9o.png",
    primaryText: "Welcome home!",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-048",
    label: "Don't Forget to Subscribe E-Commerce Text Effect in Bright Yellow Trendy Business Style",
    img: "https://template.canva.com/EAGEmCitFJw/2/0/288w-dOME0Mej9h4.png",
    primaryText: "LIKE & SUBSCRIBE",
    subText: "DON'T FORGET TO SHARE",
    fontKey: "display",
    color: "#F59E0B",
    fontSize: 36,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  {
    id: "canva-official-049",
    label: "Exclusive Heritage Text Effect in Dark Green Black Style",
    img: "https://template.canva.com/EAGTmSXSzTw/3/0/208w-WixQOxA2pKU.png",
    primaryText: "Exclusive Heritage",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-050",
    label: "Thank You For Shopping With Us E-Commerce Text Effect in Pink Trendy Business Style",
    img: "https://template.canva.com/EAGEmG8h_BQ/2/0/364w-HNXRaXF4iKQ.png",
    primaryText: "Thank You",
    subText: "FOR YOUR SUPPORT",
    fontKey: "serif",
    color: "#DB2777",
    fontSize: 40,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-051",
    label: "Point of view Text Effect in Burgundy Light Pink Experimental Type Style",
    img: "https://template.canva.com/EAGblB41jc4/2/0/682w-FAg2wZdXxb0.png",
    primaryText: "Point of view",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-052",
    label: "Bright Store Business Open 24/7 Neon Text Effect",
    img: "https://template.canva.com/EAD874Ka3OI/3/0/396w-c6Pku6PNQFE.png",
    primaryText: "BRIGHT STORE BUSINESS OPEN 24/7",
    subText: "",
    fontKey: "display",
    color: "#EAB308",
    fontSize: 36,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  {
    id: "canva-official-053",
    label: "Professional Job Hiring",
    img: "https://template.canva.com/EADYfrarHPw/1/0/1522w-olJrYCe4J0Y.png",
    primaryText: "Professional Job Hiring",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-054",
    label: "Featured Text Effect in Burgundy Classy Style",
    img: "https://template.canva.com/EAGblCQ-UyU/3/0/232w-Nad4YvtDX0A.png",
    primaryText: "Featured",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-055",
    label: "Brand Storytelling & Content Creation Text Effect in Black Style",
    img: "https://template.canva.com/EAGiJDrcwqc/1/0/286w-qG25uDxU5dE.png",
    primaryText: "Brand Storytelling & Content...",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-056",
    label: "Comic Cartoon",
    img: "https://template.canva.com/EAFxq0Ih6sM/2/0/368w-jVeg7Cngspc.png",
    primaryText: "Comic Cartoon",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-057",
    label: "Corporate Training & Team Building Text Effect in Violet Dark Blue Style",
    img: "https://template.canva.com/EAGiJDraFko/1/0/274w-UddG3xDFufs.png",
    primaryText: "Corporate Training & Team Bu...",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-058",
    label: "Soft Shadow Text Effect in Dark Green Style",
    img: "https://template.canva.com/EAGTmfwjL3M/3/0/210w-I1GASeNKzsA.png",
    primaryText: "Soft Shadow",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-059",
    label: "Shine and Sparkle Text Effect in Neon Pink Neon Style",
    img: "https://template.canva.com/EAFxf2jpjWQ/2/0/508w-HVzSQe_XWL8.png",
    primaryText: "SHINE AND SPARKLE",
    subText: "",
    fontKey: "display",
    color: "#EC4899",
    fontSize: 36,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  {
    id: "canva-official-060",
    label: "Glowing Green Sci-Fi Year 3000 Neon Text Effect",
    img: "https://template.canva.com/EAD8794v00Q/3/0/496w-U19tDPk_afQ.png",
    primaryText: "GLOWING GREEN SCI-FI YEAR 3000",
    subText: "",
    fontKey: "display",
    color: "#06B6D4",
    fontSize: 36,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  {
    id: "canva-official-061",
    label: "Perfume Label Center",
    img: "https://template.canva.com/EADYfslHasg/2/0/1100w-N-5phoLeADs.png",
    primaryText: "Perfume Label Center",
    subText: "",
    fontKey: "serif",
    color: "#374151",
    fontSize: 28,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-062",
    label: "Sale Clock Text Group",
    img: "https://template.canva.com/EADYflitm3c/2/0/806w-gBRYurpy7yo.png",
    primaryText: "BIG SALE",
    subText: "UP TO 50% OFF",
    fontKey: "sans-bold",
    color: "#DC2626",
    fontSize: 44,
    textTransform: "uppercase",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-063",
    label: "Purple and Green Chill Splice Text Effect",
    img: "https://template.canva.com/EAD88JGSG5w/3/0/416w-gs-uJJy2syc.png",
    primaryText: "Purple and Green Chill Splice",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-064",
    label: "Feeling Fancy Text Effect in Pastel Pink Curve Style",
    img: "https://template.canva.com/EAFxf7mKQ7k/2/0/784w-RM9UTzjMPNY.png",
    primaryText: "Feeling Fancy",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-065",
    label: "We're Hiring Recruitment Text Effect in Bright Blue Trendy Business Style",
    img: "https://template.canva.com/EAGEmI2MsqE/2/0/400w-XC0q5CY8znM.png",
    primaryText: "We're Hiring Recruitment",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-066",
    label: "Cursive Birthday Text Group",
    img: "https://template.canva.com/EADYfm5klTs/2/0/1368w-kyabPC3RnFA.png",
    primaryText: "Cursive Birthday",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-067",
    label: "80s Game Pixel Retro Glitch Text Effect",
    img: "https://template.canva.com/EAD87z0UX1I/2/0/772w-bNt1sFimRz4.png",
    primaryText: "80s Game Pixel Retro Glitch",
    subText: "",
    fontKey: "display",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-068",
    label: "Scary Story Text Effect in Red White Style",
    img: "https://template.canva.com/EAGDIOu7QQw/2/0/756w-uibahzN3r3o.png",
    primaryText: "Scary Story",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-069",
    label: "Official Memo",
    img: "https://template.canva.com/EADYfg608E0/1/0/1548w-U-oBLigWvu0.png",
    primaryText: "SPECIAL OFFER",
    subText: "SHOP NOW",
    fontKey: "sans-bold",
    color: "#DC2626",
    fontSize: 44,
    textTransform: "uppercase",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-070",
    label: "Homeware List",
    img: "https://template.canva.com/EADYfh9mH6A/2/0/678w-prnGKji06AY.png",
    primaryText: "Homeware List",
    subText: "",
    fontKey: "serif",
    color: "#374151",
    fontSize: 28,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-071",
    label: "Certificate Signee",
    img: "https://template.canva.com/EADYfiIA0q0/2/0/328w-7Qds9Od9YEI.png",
    primaryText: "Certificate Signee",
    subText: "",
    fontKey: "serif",
    color: "#374151",
    fontSize: 28,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-072",
    label: "Pixel and Calligraphy Text Effect in Dark Blue Style",
    img: "https://template.canva.com/EAGiOZYcEd4/1/0/670w-ddc12lTI8FI.png",
    primaryText: "Pixel and Calligraphy",
    subText: "",
    fontKey: "display",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-073",
    label: "Neon Sign Text Effect in Red Style",
    img: "https://template.canva.com/EAGDIFI7MbY/2/0/242w-L8JXtvkM2kc.png",
    primaryText: "NEON SIGN",
    subText: "",
    fontKey: "display",
    color: "#EAB308",
    fontSize: 36,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  {
    id: "canva-official-074",
    label: "Free Shipping Text Effect in Bright Red Neon Yellow Outline Style",
    img: "https://template.canva.com/EAFxf25ao5M/2/0/252w-YgSuG4YbQMc.png",
    primaryText: "FREE SHIPPING",
    subText: "",
    fontKey: "display",
    color: "#EAB308",
    fontSize: 36,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  {
    id: "canva-official-075",
    label: "Summer Trip & Vacation Planning Text Effect in Green Style",
    img: "https://template.canva.com/EAGiJPiCQBk/1/0/416w-FnM_KFj6yvQ.png",
    primaryText: "Summer Trip & Vacation Plann...",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-076",
    label: "Seasonal Exclusive Text Effect in Blue Grey Aspirational Elegance Style",
    img: "https://template.canva.com/EAGblCzqArs/2/0/210w-AftCTLbL6ZA.png",
    primaryText: "Seasonal Exclusive",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-077",
    label: "Elegant Wedding",
    img: "https://template.canva.com/EADYfkvxves/2/0/1506w-YYMtS1s45Ao.png",
    primaryText: "Our Wedding",
    subText: "JOIN OUR CELEBRATION",
    fontKey: "serif",
    color: "#1F2937",
    fontSize: 38,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-078",
    label: "You're Welcome Text Effect in Bright Orange Fuchsia Shadow Style",
    img: "https://template.canva.com/EAFxq_dz_a8/1/0/332w-GMtEodtcaP4.png",
    primaryText: "You're Welcome",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-079",
    label: "Please rate us Text Effect in Dark Blue Grey Style",
    img: "https://template.canva.com/EAGTmd8waS4/1/0/212w-euJIsfryqoU.png",
    primaryText: "Please rate us",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-080",
    label: "Lovely Text Effect in Red Pink Style",
    img: "https://template.canva.com/EAG140sH6fQ/1/0/376w-jB-Yl1MVbSk.png",
    primaryText: "Lovely",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-081",
    label: "Heading, Paragraph",
    img: "https://template.canva.com/EADYfqPTRLY/1/0/542w-RweZUGMPQAo.png",
    primaryText: "Heading, Paragraph",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-082",
    label: "Blue and Red Shop Free Delivery Shadow Text Effect",
    img: "https://template.canva.com/EAD87-T7PD8/2/0/382w-to4o8iGR5T4.png",
    primaryText: "Blue and Red Shop Free Deliv...",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-083",
    label: "Red Wine Label",
    img: "https://template.canva.com/EADYftfL7Ls/2/0/770w-v7SEZHxdxkw.png",
    primaryText: "Red Wine Label",
    subText: "",
    fontKey: "serif",
    color: "#374151",
    fontSize: 28,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-084",
    label: "Certificate of Completion Left",
    img: "https://template.canva.com/EADYfuXT-RQ/1/0/334w-U1-7NydBSSs.png",
    primaryText: "Certificate of Completion Left",
    subText: "",
    fontKey: "serif",
    color: "#374151",
    fontSize: 28,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-085",
    label: "Pink Script You're Invited Shadow Text Effect",
    img: "https://template.canva.com/EAD88Pg4mPI/2/0/378w-Z4MbcsbzVvU.png",
    primaryText: "Pink Script You're Invited S...",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-086",
    label: "Award Name Center",
    img: "https://template.canva.com/EADYfqOmz7s/2/0/742w-RC7kFbNkpuE.png",
    primaryText: "Award Name Center",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-087",
    label: "Minimalist Menu List",
    img: "https://template.canva.com/EADYfsKdtKg/2/0/404w-7AHkPTIQ0vU.png",
    primaryText: "Minimalist Menu List",
    subText: "",
    fontKey: "serif",
    color: "#374151",
    fontSize: 28,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-088",
    label: "Big Numbered Item",
    img: "https://template.canva.com/EADYfhDYJKw/2/0/1078w-pTY6PYryVto.png",
    primaryText: "Big Numbered Item",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-089",
    label: "Bold Moves Text Effect in Orange Dark Blue Style",
    img: "https://template.canva.com/EAG14w1NDUo/1/0/228w-Zi9g3snuO7Q.png",
    primaryText: "Bold Moves",
    subText: "",
    fontKey: "display",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  },
  {
    id: "canva-official-090",
    label: "Screen Break Text Effect in Black Style",
    img: "https://template.canva.com/EAG1471Tvi0/1/0/380w--zIg90tA98g.png",
    primaryText: "Screen Break",
    subText: "",
    fontKey: "serif",
    color: "#1E293B",
    fontSize: 36,
    textTransform: "none",
    letterSpacing: "0em",
  }
];

export interface CanvaTextApp {
  id: string;
  name: string;
  icon: string;
}

export const CANVA_TEXT_APPS: CanvaTextApp[] = [
  {
    id: "typestudio",
    name: "TypeStudio",
    icon: "https://thirdparty-public-apps-media.canva-apps.com/v2/BAFxvyX5Rx4/UAFxv8_zf_w/AAGrY2fIkkY/1/thumbnail/603df3e9-c7b3-4946-9b01-92e00bf93b1c_256x256.png",
  },
  {
    id: "typecraft",
    name: "TypeCraft",
    icon: "https://thirdparty-public-apps-media.canva-apps.com/v2/BADY7VL20LI/UADY7dawIQo/AAFhOgYBHhc/13/thumbnail/6266205f-2502-48b5-b9bf-a11c340ca553_256x256.png",
  },
  {
    id: "motiontext",
    name: "MotionText",
    icon: "https://thirdparty-public-apps-media.canva-apps.com/v2/BAElG4hvXXs/UAElGwfIUP8/AAGliEVOBEA/7/thumbnail/fcd33ff6-15f7-4eaf-9384-42bb4f35bd5e_256x256.png",
  },
  {
    id: "typeextrude",
    name: "TypeExtrude",
    icon: "https://thirdparty-public-apps-media.canva-apps.com/v2/BAFxvyX5Rx4/UAFxv8_zf_w/AAGB3pmX7hc/1/thumbnail/206ca79e-0943-4e5f-af18-d08e6480c434_256x256.png",
  },
  {
    id: "typecutout",
    name: "TypeCutOut",
    icon: "https://thirdparty-public-apps-media.canva-apps.com/v2/BAFxvyX5Rx4/UAFxv8_zf_w/AAGB3po4Nwg/2/thumbnail/1388fd1d-d9a6-4511-aa8c-7eeb5a976215_256x256.png",
  },
];
