import type { MagazineTemplateMeta } from '../types';

/**
 * Static template metadata — no page data, no imports beyond types.
 *
 * Kept in its own module so the library route can render search, filters and
 * card skeletons before the (much larger) page data loads, and so the sitemap
 * generator can read the slug list at build time without pulling in browser
 * code.
 */
export const TEMPLATE_INDEX: MagazineTemplateMeta[] = [
  {
    id: 'minimal-editorial',
    name: 'Minimal Editorial',
    slug: 'minimal-editorial',
    category: 'Minimal',
    description: 'Generous whitespace, a fine serif and brass accents. Built for slow, considered features.',
    pageCount: 8,
    accent: '#B08D57',
    badge: 'popular',
    keywords: ['minimal', 'editorial', 'clean', 'serif', 'whitespace', 'interiors'],
  },
  {
    id: 'luxury-fashion',
    name: 'Luxury Fashion',
    slug: 'luxury-fashion',
    category: 'Fashion',
    description: 'Near-black pages with champagne gold and full-bleed imagery for lookbooks and couture stories.',
    pageCount: 8,
    accent: '#C9A24B',
    badge: 'popular',
    keywords: ['fashion', 'luxury', 'dark', 'lookbook', 'couture', 'gold', 'runway'],
  },
  {
    id: 'modern-business',
    name: 'Modern Business',
    slug: 'modern-business',
    category: 'Business',
    description: 'A confident blue grid with stat bands and case studies for quarterly reviews and briefings.',
    pageCount: 8,
    accent: '#1B4965',
    keywords: ['business', 'report', 'strategy', 'quarterly', 'stats', 'corporate'],
  },
  {
    id: 'corporate-report',
    name: 'Corporate Annual Report',
    slug: 'corporate-report',
    category: 'Corporate',
    description: 'Formal, ruled and audit-ready. Chair statement, performance figures, governance and board pages.',
    pageCount: 8,
    accent: '#0F3D3E',
    keywords: ['annual report', 'corporate', 'governance', 'finance', 'board', 'formal'],
  },
  {
    id: 'travel-journal',
    name: 'Travel Journal',
    slug: 'travel-journal',
    category: 'Travel',
    description: 'Sun-bleached paper and terracotta accents for route diaries, photo essays and long drives.',
    pageCount: 9,
    accent: '#C2571E',
    badge: 'popular',
    keywords: ['travel', 'journal', 'route', 'photo essay', 'road trip', 'warm'],
  },
  {
    id: 'food-restaurant',
    name: 'Food & Restaurant',
    slug: 'food-restaurant',
    category: 'Food',
    description: 'Cream and olive pages with dish features, pantry listings and grower profiles.',
    pageCount: 8,
    accent: '#4F6B2A',
    keywords: ['food', 'restaurant', 'menu', 'recipe', 'produce', 'kitchen'],
  },
  {
    id: 'photography-portfolio',
    name: 'Photography Portfolio',
    slug: 'photography-portfolio',
    category: 'Photography',
    description: 'Gallery white with type kept out of the way. Full-bleed plates and mosaic series pages.',
    pageCount: 8,
    accent: '#E4572E',
    badge: 'popular',
    keywords: ['photography', 'portfolio', 'gallery', 'series', 'plates', 'documentary'],
  },
  {
    id: 'architecture-review',
    name: 'Architecture Review',
    slug: 'architecture-review',
    category: 'Architecture',
    description: 'Concrete greys, hairline rules and technical sidebars for project reviews and details.',
    pageCount: 9,
    accent: '#7A5C3E',
    keywords: ['architecture', 'review', 'project', 'technical', 'details', 'concrete'],
  },
  {
    id: 'technology-editorial',
    name: 'Technology Editorial',
    slug: 'technology-editorial',
    category: 'Technology',
    description: 'Ink-dark long-read pages with electric accents, benchmark bands and post-mortem timelines.',
    pageCount: 8,
    accent: '#3B82F6',
    badge: 'new',
    keywords: ['technology', 'engineering', 'long read', 'dark', 'benchmarks', 'software'],
  },
  {
    id: 'lifestyle-magazine',
    name: 'Lifestyle Magazine',
    slug: 'lifestyle-magazine',
    category: 'Lifestyle',
    description: 'Blush and plum with warm features, product picks and at-home photography.',
    pageCount: 8,
    accent: '#C2185B',
    keywords: ['lifestyle', 'home', 'monthly', 'warm', 'features', 'shopping'],
  },
  {
    id: 'real-estate-showcase',
    name: 'Real Estate Showcase',
    slug: 'real-estate-showcase',
    category: 'Real Estate',
    description: 'Stone and navy property portfolio with specification sidebars, guide prices and interiors.',
    pageCount: 8,
    accent: '#1F3A5F',
    keywords: ['real estate', 'property', 'listing', 'brochure', 'interiors', 'portfolio'],
  },
  {
    id: 'product-catalogue',
    name: 'Product Catalogue',
    slug: 'product-catalogue',
    category: 'Product Catalogue',
    description: 'Bright modular retail catalogue with priced ranges, finishes and ordering terms.',
    pageCount: 8,
    accent: '#E8590C',
    keywords: ['catalogue', 'product', 'retail', 'pricing', 'range', 'wholesale'],
  },
  {
    id: 'creative-studio',
    name: 'Creative Studio',
    slug: 'creative-studio',
    category: 'Creative',
    description: 'Violet capabilities deck for studios — case studies, team pages and engagement terms.',
    pageCount: 9,
    accent: '#6D28D9',
    badge: 'new',
    keywords: ['studio', 'agency', 'creative', 'case study', 'capabilities', 'portfolio'],
  },
  {
    id: 'news-editorial',
    name: 'News Editorial',
    slug: 'news-editorial',
    category: 'News',
    description: 'Newsprint greys and a red rule for investigations, data pages and right-of-reply spreads.',
    pageCount: 8,
    accent: '#B91C1C',
    keywords: ['news', 'newspaper', 'investigation', 'journalism', 'data', 'editorial'],
  },
  {
    id: 'education-magazine',
    name: 'Education Magazine',
    slug: 'education-magazine',
    category: 'Education',
    description: 'Friendly teal campus magazine with results pages, student projects and a year timeline.',
    pageCount: 8,
    accent: '#0E7490',
    keywords: ['education', 'school', 'campus', 'yearbook', 'students', 'results'],
  },
  {
    id: 'bold-typography',
    name: 'Bold Typography',
    slug: 'bold-typography',
    category: 'Editorial',
    description: 'Type as the image — heavy display faces, acid accents and photography used sparingly.',
    pageCount: 8,
    accent: '#D9F000',
    badge: 'new',
    keywords: ['typography', 'bold', 'display', 'poster', 'graphic', 'editorial'],
  },
  {
    id: 'mono-noir',
    name: 'Premium Black & White',
    slug: 'mono-noir',
    category: 'Editorial',
    description: 'Pure monochrome plates with technical notes. No colour values anywhere in the document.',
    pageCount: 8,
    accent: '#FFFFFF',
    keywords: ['black and white', 'monochrome', 'noir', 'plates', 'film', 'dark'],
  },
  {
    id: 'scandinavian-clean',
    name: 'Clean Scandinavian',
    slug: 'scandinavian-clean',
    category: 'Minimal',
    description: 'Pale, calm and generous. Cool grey-blue accents for interiors and material stories.',
    pageCount: 8,
    accent: '#8FA9B5',
    keywords: ['scandinavian', 'minimal', 'interiors', 'calm', 'light', 'materials'],
  },
  {
    id: 'modern-grid',
    name: 'Modern Grid',
    slug: 'modern-grid',
    category: 'Creative',
    description: 'Swiss grid discipline with one saturated red. Modular scale, baseline rules, exact spacing.',
    pageCount: 8,
    accent: '#E11D48',
    keywords: ['grid', 'swiss', 'modular', 'layout', 'system', 'geometric'],
  },
  {
    id: 'luxury-product',
    name: 'Luxury Product',
    slug: 'luxury-product',
    category: 'Product Catalogue',
    description: 'Espresso and gold-leaf lookbook for limited runs, made-to-order pieces and atelier stories.',
    pageCount: 8,
    accent: '#C5A059',
    badge: 'new',
    keywords: ['luxury', 'product', 'lookbook', 'jewellery', 'atelier', 'premium'],
  },
  {
    id: 'designer-portfolio',
    name: 'Designer Portfolio',
    slug: 'designer-portfolio',
    category: 'Portfolio',
    description: 'Charcoal and amber personal portfolio — project cases, outcomes and an honest about page.',
    pageCount: 9,
    accent: '#D97706',
    badge: 'new',
    keywords: ['portfolio', 'designer', 'case study', 'personal', 'freelance', 'work'],
  },
  {
    id: 'street-style',
    name: 'Street Style',
    slug: 'street-style',
    category: 'Fashion',
    description: 'Raw concrete grey with a hot pink jolt. Unstyled street fashion, shot on the block not the runway.',
    pageCount: 7,
    accent: '#FF2D6B',
    keywords: ['street style', 'fashion', 'urban', 'zine', 'skate', 'youth'],
  },
  {
    id: 'startup-pitch',
    name: 'Startup Pitch Digest',
    slug: 'startup-pitch',
    category: 'Business',
    description: 'Crisp white with electric indigo. Founder briefings, burn-rate stats and pivot case studies.',
    pageCount: 7,
    accent: '#4338CA',
    badge: 'new',
    keywords: ['startup', 'business', 'pitch', 'founders', 'metrics', 'venture'],
  },
  {
    id: 'island-escape',
    name: 'Island Escape Guide',
    slug: 'island-escape',
    category: 'Travel',
    description: 'Sea glass teal and sand. A slower, off-season coastal travel guide.',
    pageCount: 7,
    accent: '#0F8A82',
    keywords: ['travel', 'island', 'coastal', 'beach', 'off season', 'guide'],
  },
  {
    id: 'bakery-journal',
    name: 'Bakery and Pastry Journal',
    slug: 'bakery-journal',
    category: 'Food',
    description: 'Buttery cream and cocoa. Bread, lamination technique and the 4am bakery shift.',
    pageCount: 7,
    accent: '#B5651D',
    keywords: ['bakery', 'pastry', 'bread', 'food', 'recipe', 'kitchen'],
  },
  {
    id: 'wedding-album',
    name: 'Wedding Story Album',
    slug: 'wedding-album',
    category: 'Photography',
    description: 'Soft ivory and dusted rose. A wedding photography story told across a three-day celebration.',
    pageCount: 7,
    accent: '#B76E79',
    badge: 'popular',
    keywords: ['wedding', 'photography', 'album', 'bride', 'celebration', 'story'],
  },
  {
    id: 'concrete-minimal',
    name: 'Concrete and Light',
    slug: 'concrete-minimal',
    category: 'Architecture',
    description: 'Cool grey concrete with a steel-blue line. Brutalist houses examined for how they use light.',
    pageCount: 7,
    accent: '#4A5A6A',
    keywords: ['architecture', 'concrete', 'brutalist', 'minimal', 'light', 'houses'],
  },
  {
    id: 'ai-weekly',
    name: 'AI and Startups Weekly',
    slug: 'ai-weekly',
    category: 'Technology',
    description: 'Lab-white with a violet signal accent. A fast-moving weekly briefing on models and inference costs.',
    pageCount: 6,
    accent: '#7C3AED',
    badge: 'new',
    keywords: ['ai', 'technology', 'startups', 'weekly', 'briefing', 'inference'],
  },
  {
    id: 'slow-living',
    name: 'Slow Living Quarterly',
    slug: 'slow-living',
    category: 'Lifestyle',
    description: 'Warm sage and clay. A wellness and slow-living title about rest, not routines.',
    pageCount: 6,
    accent: '#7C8B5E',
    keywords: ['wellness', 'slow living', 'lifestyle', 'rest', 'mindfulness', 'quarterly'],
  },
  {
    id: 'urban-loft',
    name: 'Urban Loft Collection',
    slug: 'urban-loft',
    category: 'Real Estate',
    description: 'Industrial charcoal and copper. Converted-factory lofts with exposed brick and steel.',
    pageCount: 7,
    accent: '#B5622E',
    keywords: ['real estate', 'loft', 'industrial', 'property', 'conversion', 'brochure'],
  },
  {
    id: 'skincare-catalogue',
    name: 'Skincare Line Catalogue',
    slug: 'skincare-catalogue',
    category: 'Product Catalogue',
    description: 'Clinical white with botanical green. Ingredient-led skincare with active percentages listed.',
    pageCount: 6,
    accent: '#3F7D5C',
    keywords: ['skincare', 'beauty', 'catalogue', 'cosmetics', 'ingredients', 'product'],
  },
  {
    id: 'illustration-annual',
    name: 'Illustration Annual',
    slug: 'illustration-annual',
    category: 'Creative',
    description: 'Playful coral and cream. An open-call illustration anthology with process notes and contributor profiles.',
    pageCount: 7,
    accent: '#F2603C',
    keywords: ['illustration', 'art', 'annual', 'anthology', 'creative', 'showcase'],
  },
  {
    id: 'community-gazette',
    name: 'Community Gazette',
    slug: 'community-gazette',
    category: 'News',
    description: 'Warm newsprint with a civic blue rule. A hyper-local monthly gazette for one neighbourhood.',
    pageCount: 6,
    accent: '#1D4E89',
    keywords: ['community', 'gazette', 'local news', 'neighbourhood', 'newsletter', 'civic'],
  },
  {
    id: 'alumni-review',
    name: 'University Alumni Review',
    slug: 'alumni-review',
    category: 'Education',
    description: 'Traditional maroon and cream. Reunion coverage, alumni profiles and the scholarship fund report.',
    pageCount: 7,
    accent: '#7A1F2B',
    keywords: ['alumni', 'university', 'education', 'reunion', 'graduates', 'review'],
  },
  {
    id: 'portrait-portfolio',
    name: 'Portrait Photographer Portfolio',
    slug: 'portrait-portfolio',
    category: 'Portfolio',
    description: "Warm charcoal with a gold rule. A portrait photographer's decade of editorial and personal work.",
    pageCount: 7,
    accent: '#B08D3E',
    keywords: ['portrait', 'photography', 'portfolio', 'headshots', 'personal brand'],
  },
  {
    id: 'sustainability-report',
    name: 'Sustainability Report',
    slug: 'sustainability-report',
    category: 'Corporate',
    description: 'Forest green and warm white. An independently assured ESG report that reports the shortfalls too.',
    pageCount: 6,
    accent: '#2F6B45',
    badge: 'new',
    keywords: ['sustainability', 'esg', 'corporate', 'report', 'emissions', 'annual'],
  },
  {
    id: 'paper-ink-journal',
    name: 'Paper and Ink Journal',
    slug: 'paper-ink-journal',
    category: 'Minimal',
    description: "Uncoated paper white and printer's black. A minimal journal about letterpress craft.",
    pageCount: 6,
    accent: '#8A1F11',
    keywords: ['print', 'letterpress', 'craft', 'minimal', 'journal', 'typography'],
  },
  {
    id: 'coastal-fashion',
    name: 'Coastal Resort Fashion',
    slug: 'coastal-fashion',
    category: 'Fashion',
    description: 'Sun-washed linen and salt-faded blue. A resort collection shot on location, no studio lights.',
    pageCount: 6,
    accent: '#3F7C8A',
    keywords: ['resort', 'fashion', 'coastal', 'linen', 'summer', 'lookbook'],
  },
  {
    id: 'wanderlog-mono',
    name: 'Monochrome Travel Journal',
    slug: 'wanderlog-mono',
    category: 'Travel',
    description: 'Pure black, white and grey. A minimalist travel journal that trades colour for composition.',
    pageCount: 8,
    accent: '#111111',
    badge: 'new',
    keywords: ['travel', 'black and white', 'monochrome', 'minimalist', 'journal', 'photography'],
  },
];
